#!/bin/bash
echo "opening visualization"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
echo $DIR
cd $DIR/Visualizacion/ChartsDemo-macOS/Build-command-line/Products/Debug
open ChartsDemo-macOS.app