#!/bin/bash
echo "building visualisation"
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
echo $DIR
cd $DIR/Visualisacion
xcodebuild -project Charts.xcodeproj -scheme Charts -configuration Debug BUILD_DIR=./
cp -r Debug/Charts.framework ChartsDemo-macOS/Build-command-line/Products/Debug
cd ChartsDemo-macOS
xcodebuild -project ChartsDemo-macOS.xcodeproj -scheme ChartsDemo-macOS -configuration Debug -xcconfig command-line-build.xcconfig -derivedDataPath ./Build-command-line/DerivedData
